export enum Types {
    REQUEST_LOGIN = 'REQUEST_LOGIN',
    REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS',
    REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE',
    REQUEST_LOGOUT = 'REQUEST_LOGOUT',
    REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS',
    REQUEST_LOGOUT_FAILURE = 'REQUEST_LOGOUT_FAILURE'
}
