export enum Types {
    REQUEST_ORDER_DETAILS = 'REQUEST_ORDER_DETAILS',
    REQUEST_ORDER_DETAILS_SUCCESS = 'REQUEST_ORDER_DETAILS_SUCCESS',
    REQUEST_ORDER_DETAILS_FAILURE = 'REQUEST_ORDER_DETAILS_FAILURE'
}
